# Site settings
title: My Testweb
email: tonysu@su-networking.com	
description: > # this means to ignore newlines until "baseurl:"
  Testing only. This repo and website likely to be removed shortly
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://putztzu/github.com/testweb" # the base hostname & protocol for your site
twitter_username: is_that_simple
# github_username:  jekyll

# Build settings
markdown: kramdown
