# Site settings
title: TESTweb
email: tonysu@su-networking.com
description: > # this means to ignore newlines until "baseurl:"
  Just testing various configs. Website likely to be deleted after various tests.
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "putztzu.github.com/testweb" # the base hostname & protocol for your site
twitter_username: @This_is_just_a_test
# github_username:  

# Build settings
markdown: kramdown
